In [1]:
from graphsage.utils import load_ml20

In [12]:
import numpy as np

In [2]:
features, labels, adj_lists = load_ml20()

In [16]:
mv_count = np.array(
    [
        [0, 2, 4, 6, 8],
        [2, 0, 1, 4, 1],
        [4, 1, 0, 3, 6],
        [6, 4, 3, 0, 7],
        [8, 1, 6, 7, 0]
    ]
)

x = 5
print("--------\n threshold {}".format(x))
ed = np.sum((mv_count > x).astype(int)) / 2
print(ed)
single = np.sum(mv_count, axis=1)
print(single)
num_sin = np.sum((single == 0).astype(int))
print(num_sin)


--------
 threshold 5
4.0
[20  8 14 20 22]
0


In [17]:
mv_count[mv_count < 5] = 0

In [24]:
k = 3
u = np.array([2, 3, 2, 2, 5])
np.where(u == 2)[0]
# arr.argsort()[-k:]

array([0, 2, 3])

In [26]:
def precision_at_k(pred, true, k):
    num = len(pred)
    acc = 0
    for i in range(num):
        _y1 = pred[i].argsort()[-k:]
        _y2 = np.where(true[i] == 1)[0]
        count = 0
        for _y in _y1:
            if _y in _y2:
                count += 1
        acc += (count/k)
    return acc/num

In [28]:
pred = [[0.54545, 0, 0.2323], [0.1111, 0.771, 0]]
true = [[1, 1, 0], [0, 1, 1]]

precision_at_k(np.array(pred), np.array(true), 2)

0.5

In [1]:
import pandas as pd

m = pd.read_csv("ml-10m/movies.csv")

In [6]:
m[m.Year.isin([2006, 2007, 2008])].shape

(763, 5)

In [7]:
m[m.Year.isin([2005, 2006, 2007, 2008])].shape

(1051, 5)

In [8]:
m[m.Year<2005].shape

(6550, 5)

In [34]:
b

array([1., 1., 1., 1., 1.], dtype=float32)